# Step-by-step:
# Title
# Chat input
# On every message sent:
    # show message sent by user on the chat history
    # send this message to AI provider
    # show the answer from AI

# Python framework: streamlit -> easily handle frontend and backend
# AI: OpenAI / HuggingFace

# pip install streamlit openai huggingface_hub

import streamlit as st
# if use OpenAI
    # from openai import OpenAI
from huggingface_hub import InferenceClient

TOKEN = "your_token_here"

# if use OpenAI
    # model = OpenAI(api_key=TOKEN) 
@st.cache_resource # cache model load
def load_client():
    return InferenceClient(
        model="meta-llama/Meta-Llama-3-8B-Instruct", # quality: very good; speed: medium; resources: medium
        # model="microsoft/Phi-3-mini-4k-instruct", # quality: good; speed: high; resources: few
        token=TOKEN
    )

client = load_client()

st.write("## AI ChatBot") # accepts markdown

# st.session_state == streamlit memory (cookies)
if not "messages" in st.session_state:
    st.session_state["messages"] = []

# show the message history 
for message in st.session_state["messages"]:
    role = message["role"]
    content = message["content"]
    st.chat_message(role).write(content)

user_input = st.chat_input("Write your message here")

if user_input:
    # st chat_message roles:
        # user -> who is tipying
        # assistant -> text generated by AI

    st.chat_message("user").write(user_input)
    user_message = {"role": "user", "content": user_input}
    st.session_state["messages"].append(user_message)

    # if use OpenAI
        # model_answer = model.chat.completions.create( 
        #     messages=st.session_state["messages"],
        #     model="gpt-4o-mini"
        # )
        # ai_answer = model_answer.choices[0].message.content
    
    # AI answer
    model_answer = client.chat_completion(
        messages=st.session_state["messages"],
        max_tokens=200
    )

    ai_answer = model_answer.choices[0].message["content"]
    ai_answer += '...'

    # show AI answer at screen and add on the memory list
    st.chat_message("assistant").write(ai_answer)
    ai_message = {"role": "assistant", "content": ai_answer}
    st.session_state["messages"].append(ai_message)
